
version: '2'
services:
  aws:
      image: localstack/localstack
      environment:
        - SERVICES=iam
      ports:
        - 4593:4593
        - 8080:8080
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=lunarway
      - POSTGRES_PASSWORD=lunarway
      - POSTGRES_DB=lunarway
    ports:
      - "5432:5432"