# permissions for end users to view hubblerbacs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubblerbac-viewer-role
rules:
- apiGroups:
  - hubble.lunar.tech
  resources:
  - hubblerbacs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hubble.lunar.tech
  resources:
  - hubblerbacs/status
  verbs:
  - get
