apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hubbleroles.lunarway.com
spec:
  group: lunarway.com
  names:
    kind: HubbleRole
    listKind: HubbleRoleList
    plural: hubbleroles
    singular: hubblerole
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HubbleRole is the Schema for the hubbleroles API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HubbleRoleSpec defines the desired state of HubbleRole
          properties:
            databases:
              items:
                type: string
              type: array
            datalakeGrants:
              items:
                type: string
              type: array
            datawarehouseGrants:
              items:
                type: string
              type: array
            devDatabases:
              items:
                type: string
              type: array
            name:
              type: string
            policies:
              items:
                type: string
              type: array
          required:
          - databases
          - datalakeGrants
          - datawarehouseGrants
          - devDatabases
          - name
          - policies
          type: object
        status:
          description: HubbleRoleStatus defines the observed state of HubbleRole
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
