apiVersion: lunarway.com/v1alpha1
kind: HubbleRbac
metadata:
  name: example-hubblerbac
  namespace: datascience
spec:
  policies:
    - name: access-to-tmp-bucket
      arn: "arn:aws:iam::478824949770:policy/access-to-tmp-bucket"

  databases:
    - name: stable
      cluster: hubble-analytics.cbhx6wm2xwwx.eu-west-1.redshift.amazonaws.com
      database: prod

  devDatabases:
    - name: dev
      cluster: hubble.cbhx6wm2xwwx.eu-west-1.redshift.amazonaws.com

  roles:
    - name: BiAnalyst
      databases:
        - stable
      devDatabases:
        - dev
      datalakeGrants:
        - lw-go-events
        - eventstreams
      datawarehouseGrants:
        - public_bi
      policies:
        - access-to-tmp-bucket

  users:
    - name: jwr
      email: "jwr@lunar.app"
      roles:
        - BiAnalyst
