apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hubbledeveloperdatabases.lunarway.com
spec:
  group: lunarway.com
  names:
    kind: HubbleDeveloperDatabase
    listKind: HubbleDeveloperDatabaseList
    plural: hubbledeveloperdatabases
    singular: hubbledeveloperdatabase
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HubbleDeveloperDatabase is the Schema for the hubbledeveloperdatabases
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HubbleDeveloperDatabaseSpec defines the desired state of HubbleDeveloperDatabase
          properties:
            cluster:
              type: string
            name:
              type: string
          required:
          - cluster
          - name
          type: object
        status:
          description: HubbleDeveloperDatabaseStatus defines the observed state of
            HubbleDeveloperDatabase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
