apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hubbledatabases.lunarway.com
spec:
  group: lunarway.com
  names:
    kind: HubbleDatabase
    listKind: HubbleDatabaseList
    plural: hubbledatabases
    singular: hubbledatabase
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HubbleDatabase is the Schema for the hubbledatabases API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HubbleDatabaseSpec defines the desired state of HubbleDatabase
          properties:
            cluster:
              type: string
            database:
              type: string
            name:
              type: string
          required:
          - cluster
          - database
          - name
          type: object
        status:
          description: HubbleDatabaseStatus defines the observed state of HubbleDatabase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
